MODINREACH-361 Module Upgrade Error 'Could not commit JPA transaction'
folio-org/mod-inn-reach pull request #330
Opened 2023-03-29 12:20 UTC by Vignesh-kalyanasundaram

## Purpose
The Purpose of this PR is to fix MODINREACH-361. We can able to reproduce the issue only when there are some records with status **0** in contribution table. This issue is happening because of the wrong UserID present in folioExecutionContext.  when AuditorAwareImpl class try to fetch UserDetails with the invalid userID, Userclient is throwing FeignException. As a result, the entire transaction gets rolledback.

## Approach
Before the cancel jobs is called, we made the UserId in the folioContext as null so that AuditorAwareImpl class uses system user instead of fetching userDetails. After the fix, the records in the database are updated as per the expectation. Please find the evidence below.

<img width="960" alt="Rancher1_Before_Cancellation" src="https://user-images.githubusercontent.com/125984866/229032404-3765cce8-237a-4cd9-84b8-4618ca67ddb3.png">
<img width="960" alt="Rancher1_After_Cancellation" src="https://user-images.githubusercontent.com/125984866/229032414-d1585d2c-eb2a-450d-9042-713aac473f0b.png">

Please find the logs where there are no errors observed.
[mod-inn-reach-5994797f8-gvlj6_mod-inn-reach (1).log](https://github.com/folio-org/mod-inn-reach/files/11118527/mod-inn-reach-5994797f8-gvlj6_mod-inn-reach.1.log)

#### TODOS and Open Questions

## Learning

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

2023-03-29 13:06 UTC, TarasSpashchenko requested changes
Please use the latest version of the folio-spring-base library

2023-03-31 05:42 UTC, Vignesh-kalyanasundaram commented
> Please use the latest version of the folio-spring-base library

folio-spring-base library is updated.

2023-03-31 12:39 UTC, Arghya22 approved these changes

2023-04-04 08:01 UTC, gurleenkaurbp requested changes

2023-04-04 08:01 UTC, gurleenkaurbp commented on src/main/java/org/folio/innreach/batch/contribution/service/ContributionJobRunner.java
> +    log.info("Cancellation is done...");
Please follow logging standard message pattern.

2023-04-04 08:01 UTC, gurleenkaurbp commented on src/main/java/org/folio/innreach/batch/contribution/service/ContributionJobRunner.java
>      log.info("Cancelling unfinished contributions...");
Please change this log type to debug and restructure the message as per the logging standards.

2023-04-04 08:01 UTC, gurleenkaurbp commented on src/main/java/org/folio/innreach/domain/service/impl/FolioExecutionContextBuilder.java
> +    return builder()
Please add logs

2023-04-04 08:10 UTC, Vignesh-kalyanasundaram commented on src/main/java/org/folio/innreach/batch/contribution/service/ContributionJobRunner.java
> +    log.info("Cancellation is done...");
Removed this logger message as this may mislead even if there is no unfinished contributions.

2023-04-05 04:55 UTC, gurleenkaurbp approved these changes

2023-04-05 12:16 UTC, merged